### ISSUE TITLE
Wishlist: Provide linux binaries with releases

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#60] opened 2021-02-18 14:09 UTC

**Comment by alex-hhh** [comment] 2021-02-18 22:35
This is a good idea, but I am not using Linux, and have minimal experience with it.  This would need the help of someone who knows how to build installers for Linux and is able to test them.   In particular, it would require someone who will also be willing to continue maintaining these installers, otherwise they might become broken in the future and I won't be able to fix them...

I will add the "help wanted" label to this

**Comment by alex-hhh** [comment] 2021-02-18 22:37
Meanwhile, you can build your own distribution for Linux by following these instructions: https://github.com/alex-hhh/ActivityLog2/blob/master/docs/README.md

**Comment by idealist1508** [comment] 2021-02-19 14:26
It's pretty tricky in linux as there is no common installer, rather each distribution has its own package. As you are using azure pipeline and are building there on ubuntu, may be it is possible to make an appimage there? To my best knowledge (not an expert) after that the application should work on any linux.

Other  possible solutions(and their drawbacks):

1. simple tar with binaries (dependency checks are imposible).
2. package for ubuntu (not suitable for other distributions).

Please let me know, if you need some help with testing, I'm using arch.

**Comment by idealist1508** [comment] 2021-02-22 15:30
After I tried to use it for some time under linux, I understand now, what you meant by "maintaining". 
I found some issues, that exist only under linux.   It seems to be hard to resolve this issue at the moment, so maybe its a good idea to close this.

**Comment by alex-hhh** [comment] 2021-02-23 01:35
I will leave this issue open for now.  Other software is built and packaged for Linux, so it is certainly possible to do so, it is just that I don't know how to do it.  It costs nothing to leave this issue open and maybe someone will come along and be able to help out.

Meanwhile, it would be good if you added a comment about the things you tried and what issues you found -- this information could be useful in the future if someone picks up this task.

**Comment by idealist1508** [comment] 2021-02-24 11:56
Issue with a themes. Colors are not optimal.
![grafik](https://user-images.githubusercontent.com/4608274/108997172-94027a00-769f-11eb-81fc-a45bab6887bb.png)

**Comment by idealist1508** [comment] 2021-02-24 12:05
Extra button in Sessions -> Charts. Application friezes after click on it with a message  
> Gtk: gtk_css_gadget_queue_allocate: assertion 'GTK_IS_CSS_GADGET (gadget)' failed
![grafik](https://user-images.githubusercontent.com/4608274/108998274-f8720900-76a0-11eb-8ecf-6d6f91c66f34.png)

**Comment by idealist1508** [comment] 2021-02-24 12:25
Graphs are slow on big resolutions.
![slow](https://user-images.githubusercontent.com/4608274/109000276-c7df9e80-76a3-11eb-8f1c-f5687b37362c.gif)

**Comment by idealist1508** [comment] 2021-02-24 16:38
Size of components not optimal in Sessions -> Charts -> Graphs. 
![grafik](https://user-images.githubusercontent.com/4608274/109033499-fe7ae080-76c6-11eb-9149-60c6e66b27ea.png)

**Comment by alex-hhh** [comment] 2021-02-25 01:14
Thanks for providing these screenshots.  It looks like I misunderstood your request:  I thought you had problems with creating an installer on Linux, but it looks like you have problems with the application itself.   In any case, the slow charts might be related to #56 , and for the issue with component sizes:

![](https://user-images.githubusercontent.com/4608274/109033499-fe7ae080-76c6-11eb-9149-60c6e66b27ea.png)

Can you apply the following patch to see if this fixes it?  I think the GTK GUI behaves differently than the Windows one...

```diff
 rkt/session-inspector/inspect-graphs.rkt | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/rkt/session-inspector/inspect-graphs.rkt b/rkt/session-inspector/inspect-graphs.rkt
index f723b19..748539a 100644
--- a/rkt/session-inspector/inspect-graphs.rkt
+++ b/rkt/session-inspector/inspect-graphs.rkt
@@ -1886,6 +1886,8 @@
         (send x-axis-choice clear)
         (for-each (lambda (x) (send x-axis-choice append (car x))) x-axis-choices)
 
+        (send control-panel reflow-container)
+
         (let* ((sport-x-axis (hash-ref x-axis-by-sport (session-sport session) 0)))
           ;; We have an ambiguity here, as the open water swim has 3 choices,
           ;; but lap swimming only two.  Our X-AXIS-BY-SPORT hash only
```

**Comment by idealist1508** [comment] 2021-02-25 13:46
Thanks for the patch. I tried it out, but unfoturnatly it didn't fix the problem. The controls still look the same. 
Should I rather open extra issues instead of my comments?

**Comment by alex-hhh** [comment] 2021-03-01 09:33
I think it would be better if you opened separate issues for each defect that you find.  There will be less confusion in the discussion if each defect is a separate issue.

**Comment by alex-hhh** [comment] 2021-07-04 04:39
It is unclear what, if anything, can be done for this issue, so I will close it.  There are multiple problems reported here, but I cannot do anything about them, as I don't use Linux and I cannot reproduce them on Windows. 

@idealist1508 , if you think that any of the issues reported in the comments above are important to you, please create a separate issue for each one.

**Closed by alex-hhh** 2021-07-04 04:39 UTC
Labels: wontfix
