### ISSUE TITLE
Missing run power from Styrd power meter

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#27] opened 2018-06-29 10:45 UTC
I usually run with a Stryd so today I decided to import one of my runs...

ActivityLog2 detected my power meter in equipment. Hurray!
![2018-06-29-124418_308x93_scrot](https://user-images.githubusercontent.com/7911/42088560-2c3a23d0-7b9a-11e8-9640-17f0798e9228.png)

But unfortunately none of the stats/charts/scatter allow power to be selected. I am happy to add this feature to ActivityLog2 if you provide some background on where this data is kept how the charts are generated. Thanks.

**Comment by alex-hhh** [comment] 2018-06-29 11:57
Yes, data from a Styrd is not imported.   Since I don't have one, I didn't add support for it...  However, the application is designed to be able to add new data series with relative ease, although it would still take a few days to do it...

Here is an outline of what is needed to support 1 Styrd sensor.  If you are interested in doing the work, I can provide more details and I can help you out as much as I can.

## Reading the data from the FIT file

The fit file reader should already decode the Styrd data (these are developer fields).  You will need to identify them, however.  The simplest way is to read and inspect the decoded data, which can be done by running this code (there is more detail in the "doc/fit-read.md" file):

```
(require "fit-file.rkt")
(define activity (read-activity-from-file "activity.fit"))
```
`activity` contains one gigantic alist, but it should be relatively easy to follow.

## Importing the data into the database

The next step is to import the data into the database.  The main table for this is `A_TRACKPOINT` (see "sql/db-schema.sql" for the schema definition).

The Styrd produces some other data fields in addition to power.  If you want to add these, we can add a complete set of Styrd fields to this table.  A database patch is required for this, it is not too hard to write and I can offer some assistance if you want to go this way.

Alternatively, you can import the data into the power field only, in which case, you will just need to update the `db-insert-trackpoint` function in "rkt/database.rkt" (for power only, see how the "tile-code" field is done).

## Plots

If you just inserted the power field, it should appear as an available plot for your run activities.  If not, let me know what does not work and I can help you fix this.

If the A_TRACKPOINT table is updated with the Styrd fields, they will need to be loaded in "Session-df.rkt" (athe SQL query will need updating).  In addition to this, new `series-medatada%` objects will need to be defined for each of the new fields (there are plenty of examples in "rkt/series-meta.rkt" and these new objects listed in the various places where the graphs are created.  This will get the new data series show up in all the plots that the application generates (including the trend plots).

**Comment by alex-hhh** [comment] 2018-06-29 12:48
I should perhaps clarify that the reason that power and other data fields are not available for selection is because the Styrd data is not imported in the database.  The GUI will only allow selecting series for which data is present in the database for an activity, and Styrd data (power and other metrics) are not currently imported.

**Comment by pmatos** [comment] 2018-07-02 07:07
Thanks for the clarifications. I will submit a pull request with this implemented. If I have further questions, I will get back to you.

**Comment by alex-hhh** [comment] 2018-07-02 11:12
Looks like the Styrd adds the following data series to an activity:

* Power
* Cadence
* Ground Time (Ground Contact Time)
* Vertical Oscillation
* Form Power
* Leg Spring Stiffness

... and these fields are collected in addition to the main ones: a Garmin watch will also collect Cadence, Ground Contact Time (GCT) and Vertical Oscillation (VOSC); so there will be 2 Cadence, 2 GCT and 2 VOSC series in a running activity.

I wonder what would happen if two Styrd sensors are present (left and right) and how to best handle this?

It seems that there is also a Garmin Connect IQ application which also collects running power in the "Running Power" series.  This one at least has no left-right option.  A user could also enable this in addition to their Styrd fields, so there might be up to 3 power series in an activity.

https://connect.garmin.com/modern/activity/2008781470
https://www.dcrainmaker.com/2017/10/garmin-running-power.html

----

I wonder if it would be better to define a separate `STYRD_TRACKPOINT` and `STYRD_SECTION_SUMMARY`  tables, something like this:

```sql
create table STRYD_TRACKPOINT (
  id integer not null primary key autoincrement,
  trackpoint_id integer not null,

  power real,
  cadence real,
  stance_time real,                     -- (a.k.a ground contact time), milliseconds
  vertical_oscillation real,            -- cm
  vosc real,
  form_power real,
  leg_sprint_stiffness real

  foreign key (trackpoint_id) references A_TRACKPOINT(id));

create table STRYD_SECTION_SUMMARY (
  id integer not null primary key autoincrement,
  summary_id integer not null,

  avg_power real,
  max_power real,
  avg_cadence real,
  max_cadence real,
  avg_stance_time real,           -- (a.k.a ground contact time), milliseconds
  avg_vertical_oscillation real,      -- cm
  avg_form_power real,
  avg_leg_sprint_stiffness real,

  foreign key (summary_id) references SECTION_SUMMARY(id) on delete cascade);
```

The database importer would import data into these tables and `make-session-data-frame` (from "rkt/session-df.rkt" would add the relevant series to the data frame, if they are present.

**Comment by alex-hhh** [comment] 2018-07-19 08:43
Hi @pmatos , I have added some code to the `stryd-power` branch which should allow importing running data from a Stryd power meter.  I'm not sure if it works, as I don't have one.  Also this will only import power data, not the other metrics that Stryd collects.

Can you please try it out and see if it works for you?

For the more general case, I have decided to implement these "developer fields" in a mode generic way, calling it XDATA (as GoldenCheetah calls them).  This way any data field would be supported and graphs and reports would work as well.  I have created a project to track progress, for now it is in the planning phase, just sketching out some ideas.  If you are interested in helping out, you are welcome.

**Comment by pmatos** [comment] 2018-07-19 09:04
Wow, sounds great. Let me take a look at the code you added and have a go at it. I will get back to you on this later today. Have a couple of workouts files to generate until then. ;)

**Comment by pmatos** [comment] 2018-08-16 15:31
So, with a few holidays in between I am back (but on hols again next week and in beginning of September), I tried branch `stryd-power` and I get a few issues loading the attached file.
[2936577475.zip](https://github.com/alex-hhh/ActivityLog2/files/2294223/2936577475.zip)
 
```
convert-pace->m/s: contract violation
  expected: Positive-Real
  given: 0
  in: the 1st argument of
      (-> Positive-Real any)
  contract from: 
      /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt
  blaming: /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt
   (assuming the contract is correct)
  at: /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt:190.9
  context...:
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/blame.rkt:347:0: raise-blame-error16
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:361:33
   /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt:448:6
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:644:4: draw-marker-at method in graph-view%
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1980:56: for-loop
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1978:52
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:357:33
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/plot-gui-lib/plot/private/gui/snip2d.rkt:261:4: on-event method in 2d-plot-snip%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/pasteboard.rkt:250:2: on-event method in pasteboard%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:401:2: on-event method in editor-canvas%
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:785:4: dispatch-on-event method in window%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:627:3
convert-pace->m/s: contract violation
  expected: Positive-Real
  given: 0
  in: the 1st argument of
      (-> Positive-Real any)
  contract from: 
      /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt
  blaming: /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt
   (assuming the contract is correct)
  at: /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt:190.9
  context...:
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/blame.rkt:347:0: raise-blame-error16
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:361:33
   /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt:448:6
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:644:4: draw-marker-at method in graph-view%
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1980:56: for-loop
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1978:52
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:357:33
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/plot-gui-lib/plot/private/gui/snip2d.rkt:261:4: on-event method in 2d-plot-snip%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/pasteboard.rkt:250:2: on-event method in pasteboard%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:401:2: on-event method in editor-canvas%
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:785:4: dispatch-on-event method in window%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:627:3
convert-pace->m/s: contract violation
  expected: Positive-Real
  given: 0
  in: the 1st argument of
      (-> Positive-Real any)
  contract from: 
      /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt
  blaming: /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt
   (assuming the contract is correct)
  at: /home/pmatos/Projects/ActivityLog2/rkt/fmt-util.rkt:190.9
  context...:
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/blame.rkt:347:0: raise-blame-error16
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:361:33
   /home/pmatos/Projects/ActivityLog2/rkt/series-meta.rkt:448:6
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:644:4: draw-marker-at method in graph-view%
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1980:56: for-loop
   /home/pmatos/Projects/ActivityLog2/rkt/session-inspector/inspect-graphs.rkt:1978:52
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/contract/private/arrow-higher-order.rkt:357:33
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/plot-gui-lib/plot/private/gui/snip2d.rkt:261:4: on-event method in 2d-plot-snip%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/pasteboard.rkt:250:2: on-event method in pasteboard%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:401:2: on-event method in editor-canvas%
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pmatos/installs/racket-6.90.0.901/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:785:4: dispatch-on-event method in window%
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32
   /home/pmatos/installs/racket-6.90.0.901/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:627:3
```

**Comment by alex-hhh** [comment] 2018-08-18 00:53
I have pushed some commits to the `stryd-power` branch, can you please pull them in and try again? 

* the code was mapping developer to native fields incorrectly -- I did not have a Stryd file for testing.  This is now fixed, but you will need to delete and re-import your activity
* I could not reproduce the errors above, but I fixed similar ones on the `master` branch, so I merged `master` into `stryd-power`.  These errors affect the GUI only, the data is OK in the database.

## problems with this approach

I have tested the `styrd-power` branch with some other FIT files and it will replace a native field in a record where it is missing with the developer field -- this can result data series containing a mix of data.  

The case in point was that Garmin Vertical Oscillation (VOSC) data is missing in some records and in those records it will be replaced with the Stryd VOSC in those records only -- this means that the VOSC series contains mixed data from both Garmin and Stryd.   Garmin does the same thing with their own sensors some time: for example, it records cadence from a Speed Cadence sensor, but than switches with the Cadence from the Power Meter -- however there are special messages in the FIT file to indicate the sensor switch.

## xdata-series branch

I started work to support developer data series propertly, you can find this on the `xdata-series` branch, and track it on the `xdata-series` project here on GitHub.  The current status is that it loads the data in the database and can read it back inside the application, but it does nothing with it as of now. 

I would **not** recommend trying it out yet, unless you want to work on it -- the code contains a database upgrade patch, which is still subject to change -- if you upgrade your database, you will have to do some manual database adjustments if this patch changes.  It is not terribly difficult, but requires you to be comfortable with SQL.

Unfortunately, I will not have much time available to work on this in the next two weeks.

**Comment by alex-hhh** [comment] 2018-09-15 00:44
I have merged the xdata-series branch onto master, and master now has support for importing and visualizing XDATA series.  This is implemented in the following commits:

* https://github.com/alex-hhh/ActivityLog2/commit/88e418752e898a38c426841b5b46b1b4eaf7a73a
* https://github.com/alex-hhh/ActivityLog2/commit/4f889281ac7f5210c9ee69b07fccebec296dc31c
* https://github.com/alex-hhh/ActivityLog2/commit/842270cac93e711ea5dddadb2e7aed1923a77737
* https://github.com/alex-hhh/ActivityLog2/commit/dbc876d5f71565f756ac94d24c944d1e2a1a158b

I only have it some limited testing, as I don't use these features myself.  If you try it out, please report any problem you find as separate issues.

**Closed by alex-hhh** 2018-09-15 00:44 UTC
Labels: enhancement

**Comment by pmatos** [comment] 2018-09-16 09:07
xdata looks good, thanks. Attached screenshot.
![2018-09-16-110618_1920x1080_scrot](https://user-images.githubusercontent.com/7911/45594789-b9eca600-b9a0-11e8-8188-8cb6460863ea.png)
